const zh = {
  consoleTitle: '本周热门模型',
  consoleIntro: '精选近 7 天调用次数最高的 10 个公开模型，比较分组价格，快速接入。',
  catalogTitle: '热门模型 TOP 10',
  refresh: '刷新模型目录',
  headline: '让每一个想法，',
  headlineAccent: '找到合适的模型。',
  intro:
    '在万物，探索不同模型的接入方式与价格。从第一行代码开始，让你的下一个创意成为现实。',
  explore: '探索模型',
  getKey: '获取 API 密钥',
  artCaption: '多种模型 · 更多可能',
  models: '个模型条目',
  providers: '家模型厂商',
  routes: '个接入分组',
  statsNote: '近 7 天调用热度 · 每 5 分钟更新',
  browse: '探索模型广场',
  priceUnit: '人民币 / 百万 tokens · 中转实付起价',
  providerFilter: '模型厂商',
  groupFilter: '接入分组',
  allGroups: '全部分组',
  all: '全部模型',
  chooseTitle: '找到适合你的接入方式',
  chooseNote:
    '同一模型可能提供多个分组。展开详情，比较分组价格、缓存与计费规则。',
  search: '搜索模型名称、厂商或分组…',
  sort: '排序方式',
  sortPopular: '按调用热度',
  sortName: '按模型名称',
  sortPrice: '输入价格从低到高',
  view: '展示方式',
  cardView: '模型卡片',
  tableView: '分组价格表',
  results: '个模型条目',
  reset: '清除筛选',
  standardPrice: '各项为当前分组最低报价 · — 表示未提供该项价格',
  loading: '正在加载模型',
  loadFailed: '模型目录暂时加载失败',
  retryNote: '请检查网络后重试，已配置的模型不会受到影响。',
  retry: '重新加载',
  noSearchResult: '没有找到匹配的模型',
  searchNote: '试试更短的关键词，或清除厂商筛选。',
  emptyTitle: '暂无近期调用记录',
  emptyNote: '近 7 天暂无符合条件的公开模型调用记录，榜单将在有记录后自动更新。',
  configure: '配置模型分组',
  modelSummary: '查看接入分组与计费详情，选择适合你的使用方案。',
  routeCount: '个接入分组',
  input: '输入起价',
  output: '输出起价',
  cacheRead: '缓存读取（命中）起价',
  cacheWrite: '缓存写入起价',
  cacheWrite1h: '缓存写入（1 小时）起价',
  details: '查看价格与接入',
  close: '关闭详情',
  detailsNote:
    '以下均为中转实付价（人民币），已计入分组倍率；高峰与缓存价格见明细。充值 ¥1 = 1 余额单位。目录不代表实时可用性。',
  copy: '复制模型 ID',
  copied: '已复制',
  copyError: '复制失败，请手动选择上方模型 ID。',
  imageModel: '图像生成',
  videoModel: '视频生成',
  requestModel: '按次计费',
  languageModel: '语言模型',
  startTitle: '从一个想法，到一次调用。',
  startNote: '选好模型，创建密钥，接入你的应用或开发工具。',
  stepOne: '登录控制台，选择可用分组',
  stepTwo: '创建 API 密钥，复制模型 ID',
  stepThree: '配置对应接口，开始你的首次调用',
  anonymousHint: '登录后可查看专属倍率，并创建 API 密钥'
}
const en: Record<keyof typeof zh, string> = {
  consoleTitle: 'Trending this week',
  consoleIntro:
    'The 10 most-used public models over the last 7 days. Compare group prices and connect.',
  catalogTitle: 'Top 10 models',
  refresh: 'Refresh model catalog',
  headline: 'Every idea deserves',
  headlineAccent: 'the right model.',
  intro:
    'Explore model access and pricing on Wanwu. Start with a line of code and bring your next idea to life.',
  explore: 'Explore models',
  getKey: 'Get an API key',
  artCaption: 'More models. More possibilities.',
  models: 'model entries',
  providers: 'providers',
  routes: 'access groups',
  statsNote: 'Last 7 days · updated every 5 minutes',
  browse: 'Explore the collection',
  priceUnit: 'CNY / 1M tokens · relay starting prices',
  providerFilter: 'PROVIDERS',
  groupFilter: 'Access group',
  allGroups: 'All groups',
  all: 'All models',
  chooseTitle: 'Find your way to connect',
  chooseNote:
    'A model can have multiple access groups. Open its details to compare pricing, caching and billing rules.',
  search: 'Search models, providers or groups…',
  sort: 'Sort by',
  sortPopular: 'Most used',
  sortName: 'Model name',
  sortPrice: 'Input price: low to high',
  view: 'View mode',
  cardView: 'Model cards',
  tableView: 'Group price tables',
  results: 'model entries',
  reset: 'Clear filters',
  standardPrice: 'Lowest quote per item across selected groups · — means no price provided',
  loading: 'Loading models',
  loadFailed: 'Unable to load the model catalog',
  retryNote:
    'Check your connection and try again. Your configured models are unaffected.',
  retry: 'Try again',
  noSearchResult: 'No matching models',
  searchNote: 'Try a shorter search or clear the provider filter.',
  emptyTitle: 'No recent model usage',
  emptyNote:
    'No eligible public model calls were recorded in the last 7 days. Rankings appear automatically as usage is recorded.',
  configure: 'Configure model groups',
  modelSummary:
    'Compare access groups and billing details to find the right setup for your project.',
  routeCount: 'access groups',
  input: 'Input from',
  output: 'Output from',
  cacheRead: 'Cache read (hit) from',
  cacheWrite: 'Cache write from',
  cacheWrite1h: 'Cache write (1 hour) from',
  details: 'Pricing & access',
  close: 'Close details',
  detailsNote:
    'Relay prices are in CNY and include group rates. See details for caching and peak hours. CNY 1 funds 1 balance unit. Listings are not live availability guarantees.',
  copy: 'Copy model ID',
  copied: 'Copied',
  copyError: 'Could not copy. Select and copy the model ID above.',
  imageModel: 'Image',
  videoModel: 'Video',
  requestModel: 'Per request',
  languageModel: 'Language',
  startTitle: 'From an idea to your first call.',
  startNote:
    'Choose a model, create a key and connect your application or development tools.',
  stepOne: 'Sign in and choose an available group',
  stepTwo: 'Create an API key and copy the model ID',
  stepThree: 'Configure the matching API and make your first call',
  anonymousHint: 'Sign in for personalized rates and API keys'
}
export const catalogCopy = { zh, en }
